"""Pinned browser-use init template metadata and integrity hashes.

Generated from browser-use/template-library main on 2026-04-22.
"""

TRUSTED_INIT_TEMPLATES = {'default': {'file': 'default_template.py',
             'description': 'Simplest setup - capable of any web task with minimal configuration',
             'author': {'name': 'Reagan Hsu',
                        'github_profile': 'https://github.com/Cheggin',
                        'last_modified_date': '2025-11-11'}},
 'advanced': {'file': 'advanced_template.py',
              'description': 'All configuration options shown with defaults',
              'author': {'name': 'Reagan Hsu',
                         'github_profile': 'https://github.com/Cheggin',
                         'last_modified_date': '2025-11-11'}},
 'tools': {'file': 'tools_template.py',
           'description': 'Custom tool example - extend agent capabilities with your own functions',
           'author': {'name': 'Reagan Hsu',
                      'github_profile': 'https://github.com/Cheggin',
                      'last_modified_date': '2025-11-11'}},
 'sandbox': {'file': 'sandbox/main.py',
             'description': 'Cloud browser automation with @sandbox decorator for persistent auth and proxy routing',
             'featured': True,
             'files': [{'source': 'sandbox/main.py', 'dest': 'main.py'},
                       {'source': 'sandbox/pyproject.toml.template', 'dest': 'pyproject.toml'},
                       {'source': 'gitignore.template', 'dest': '.gitignore'},
                       {'source': 'sandbox/.env.example.template', 'dest': '.env.example'},
                       {'source': 'sandbox/README.md', 'dest': 'README.md'}],
             'next_steps': [{'title': 'Navigate to project directory', 'commands': ['cd {template}']},
                            {'title': 'Set up your API key',
                             'commands': ['cp .env.example .env', '# Edit .env and add your BROWSER_USE_API_KEY'],
                             'note': '(Get your key at '
                                     'https://cloud.browser-use.com/dashboard/settings?tab=api-keys&new)'},
                            {'title': '(Optional) Create a cloud profile for persistent authentication',
                             'commands': ['# Visit https://cloud.browser-use.com/#settings/profiles',
                                          '# Create a profile, log in to your target site, and copy the Profile ID',
                                          '# Add CLOUD_PROFILE_ID to .env']},
                            {'title': 'Install dependencies', 'commands': ['uv sync']},
                            {'title': 'Run the script', 'commands': ['uv run {output}']},
                            {'footer': '📖 See README.md for cloud configuration options and troubleshooting'}],
             'author': {'name': 'Shawn Pana',
                        'github_profile': 'https://github.com/ShawnPana',
                        'last_modified_date': '2025-11-13'}},
 'shopping': {'file': 'shopping/main.py',
              'description': 'E-commerce automation with structured output (Pydantic models)',
              'files': [{'source': 'shopping/main.py', 'dest': 'main.py'},
                        {'source': 'shopping/launch_chrome_debug.py',
                         'dest': 'launch_chrome_debug.py',
                         'executable': True},
                        {'source': 'shopping/pyproject.toml.template', 'dest': 'pyproject.toml'},
                        {'source': 'gitignore.template', 'dest': '.gitignore'},
                        {'source': 'shopping/.env.example.template', 'dest': '.env.example'},
                        {'source': 'shopping/README.md', 'dest': 'README.md'}],
              'next_steps': [{'title': 'Navigate to project directory', 'commands': ['cd {template}']},
                             {'title': 'Set up your API key',
                              'commands': ['cp .env.example .env', '# Edit .env and add your BROWSER_USE_API_KEY'],
                              'note': '(Get your key at '
                                      'https://cloud.browser-use.com/dashboard/settings?tab=api-keys&new)'},
                             {'title': 'Install dependencies', 'commands': ['uv sync']},
                             {'title': 'Launch Chrome with debugging (in a separate terminal)',
                              'commands': ['python launch_chrome_debug.py'],
                              'note': '(Run with --help to see options like --profile)\n(Keep this terminal open!)'},
                             {'title': 'Run your script (in a NEW terminal)',
                              'commands': ['cd {template} && uv run {output}']},
                             {'footer': '📖 See README.md for detailed instructions'}],
              'author': {'name': 'Shawn Pana',
                         'github_profile': 'https://github.com/ShawnPana',
                         'last_modified_date': '2025-11-11'}},
 'job-application': {'file': 'job-application/main.py',
                     'description': 'Automated job application form submission with resume upload',
                     'files': [{'source': 'job-application/main.py', 'dest': 'main.py'},
                               {'source': 'job-application/pyproject.toml.template', 'dest': 'pyproject.toml'},
                               {'source': 'gitignore.template', 'dest': '.gitignore'},
                               {'source': 'job-application/.env.example.template', 'dest': '.env.example'},
                               {'source': 'job-application/README.md', 'dest': 'README.md'},
                               {'source': 'job-application/applicant_data.json', 'dest': 'applicant_data.json'},
                               {'source': 'job-application/example_resume.pdf',
                                'dest': 'example_resume.pdf',
                                'binary': True}],
                     'next_steps': [{'title': 'Navigate to project directory', 'commands': ['cd {template}']},
                                    {'title': 'Set up your API key',
                                     'commands': ['cp .env.example .env', '# Edit .env and add your GOOGLE_API_KEY'],
                                     'note': '(Get your key at https://aistudio.google.com/app/apikey)'},
                                    {'title': 'Install dependencies', 'commands': ['uv sync']},
                                    {'title': 'Customize your data',
                                     'commands': ['# Edit applicant_data.json with your information',
                                                  '# Replace example_resume.pdf with your resume']},
                                    {'title': 'Run the application',
                                     'commands': ['uv run {output} --resume example_resume.pdf']},
                                    {'footer': '📖 See README.md for customization and troubleshooting'}],
                     'author': {'name': 'Shawn Pana',
                                'github_profile': 'https://github.com/ShawnPana',
                                'last_modified_date': '2025-11-11'}},
 'agentmail': {'file': 'agentmail/main.py',
               'description': 'Email inbox automation with 2FA support using AgentMail',
               'files': [{'source': 'agentmail/main.py', 'dest': 'main.py'},
                         {'source': 'agentmail/email_tools.py', 'dest': 'email_tools.py'},
                         {'source': 'agentmail/pyproject.toml.template', 'dest': 'pyproject.toml'},
                         {'source': 'gitignore.template', 'dest': '.gitignore'},
                         {'source': 'agentmail/.env.example.template', 'dest': '.env.example'},
                         {'source': 'agentmail/README.md', 'dest': 'README.md'}],
               'next_steps': [{'title': 'Navigate to project directory', 'commands': ['cd {template}']},
                              {'title': 'Set up your API keys',
                               'commands': ['cp .env.example .env',
                                            '# Edit .env and add your AGENTMAIL_API_KEY and BROWSER_USE_API_KEY'],
                               'note': '(Get AgentMail key at '
                                       'https://docs.agentmail.to/api-reference/api-keys/create)\n'
                                       '(Get Browser-Use key at '
                                       'https://cloud.browser-use.com/dashboard/settings?tab=api-keys&new)'},
                              {'title': 'Install dependencies', 'commands': ['uv sync']},
                              {'title': 'Run the script', 'commands': ['uv run {output}']},
                              {'footer': '📖 See README.md for customization and advanced usage'}],
               'author': {'name': 'Magnus Müller',
                          'github_profile': 'https://github.com/MagMueller',
                          'last_modified_date': '2025-11-11'}},
 'llm-arena': {'file': 'llm-arena/main.py',
               'description': 'Compare different AI models side-by-side in LLM Arena',
               'files': [{'source': 'llm-arena/main.py', 'dest': 'main.py'},
                         {'source': 'llm-arena/pyproject.toml.template', 'dest': 'pyproject.toml'},
                         {'source': 'gitignore.template', 'dest': '.gitignore'},
                         {'source': 'llm-arena/.env.example.template', 'dest': '.env.example'},
                         {'source': 'llm-arena/README.md', 'dest': 'README.md'}],
               'next_steps': [{'title': 'Navigate to project directory', 'commands': ['cd {template}']},
                              {'title': 'Set up your API keys',
                               'commands': ['cp .env.example .env',
                                            '# Edit .env and add your API keys for the LLMs you want to compare'],
                               'note': '(Required: BROWSER_USE_API_KEY from https://browser-use.com/)\n'
                                       '(Optional but recommended: GOOGLE_API_KEY, OPENAI_API_KEY, ANTHROPIC_API_KEY)\n'
                                       '(See README.md for links to get each API key)'},
                              {'title': 'Install dependencies', 'commands': ['uv sync']},
                              {'title': 'Run the comparison', 'commands': ['uv run {output}']},
                              {'footer': '📖 See README.md for customization and advanced usage\n'
                                         '\n'
                                         '⚡ Enter a task and watch LLMs race to complete it!'}],
               'author': {'name': 'Shawn Pana',
                          'github_profile': 'https://github.com/ShawnPana',
                          'last_modified_date': '2025-11-11'}},
 'slack': {'file': 'slack/README.md',
           'description': 'Slack bot for browser automation tasks via mentions',
           'files': [{'source': 'slack/app/main.py', 'dest': 'app/main.py'},
                     {'source': 'slack/app/service.py', 'dest': 'app/service.py'},
                     {'source': 'slack/pyproject.toml.template', 'dest': 'pyproject.toml'},
                     {'source': 'gitignore.template', 'dest': '.gitignore'},
                     {'source': 'slack/.env.example.template', 'dest': '.env.example'},
                     {'source': 'slack/README.md', 'dest': 'README.md'}],
           'next_steps': [{'title': 'Navigate to project directory', 'commands': ['cd {template}']},
                          {'title': 'Set up your API keys',
                           'commands': ['cp .env.example .env',
                                        '# Edit .env and add your BROWSER_USE_API_KEY, SLACK_ACCESS_TOKEN, and '
                                        'SLACK_SIGNING_SECRET'],
                           'note': '(Get Browser-Use key at '
                                   'https://cloud.browser-use.com/dashboard/settings?tab=api-keys&new)\n'
                                   '(Get Slack credentials from https://api.slack.com/apps)'},
                          {'title': 'Install dependencies', 'commands': ['uv sync']},
                          {'title': 'Create and configure Slack app',
                           'commands': ["# Follow README.md section 'Create Slack App' for detailed instructions"],
                           'note': '(Set OAuth scopes: app_mentions:read, channels:read, chat:write)'},
                          {'title': 'Start ngrok tunnel (for local development)',
                           'commands': ['ngrok http 8000'],
                           'note': '(Keep this terminal open and copy the HTTPS URL)'},
                          {'title': 'Run the application (in a NEW terminal)',
                           'commands': ['cd {template} && uv run app/main.py']},
                          {'footer': '📖 See README.md for detailed setup, Event Subscriptions configuration, and '
                                     'production deployment'}],
           'author': {'name': 'Shawn Pana',
                      'github_profile': 'https://github.com/ShawnPana',
                      'last_modified_date': '2025-11-11'}},
 'all-openai-jobs': {'file': 'all-openai-jobs/main.py',
                     'description': 'Web scraping with CodeAgent to extract job listings from career pages',
                     'featured': True,
                     'files': [{'source': 'all-openai-jobs/main.py', 'dest': 'main.py'},
                               {'source': 'all-openai-jobs/pyproject.toml.template', 'dest': 'pyproject.toml'},
                               {'source': 'gitignore.template', 'dest': '.gitignore'},
                               {'source': 'all-openai-jobs/.env.example.template', 'dest': '.env.example'},
                               {'source': 'all-openai-jobs/README.md', 'dest': 'README.md'}],
                     'next_steps': [{'title': 'Navigate to project directory', 'commands': ['cd {template}']},
                                    {'title': 'Set up your API key',
                                     'commands': ['cp .env.example .env',
                                                  '# Edit .env and add your BROWSER_USE_API_KEY'],
                                     'note': '(Get your key at '
                                             'https://cloud.browser-use.com/dashboard/settings?tab=api-keys&new)'},
                                    {'title': 'Install dependencies', 'commands': ['uv sync']},
                                    {'title': 'Run the job scraper', 'commands': ['uv run {output}']},
                                    {'footer': '📖 See README.md for customization and troubleshooting\n'
                                               '\n'
                                               '🤖 CodeAgent will generate extraction code and save it to '
                                               'script.ipynb'}],
                     'author': {'name': 'kalil0321',
                                'github_profile': 'https://github.com/kalil0321',
                                'last_modified_date': '2025-11-07'}},
 'scheduler': {'file': 'scheduler/main.py',
               'description': 'Multi-agent scheduler that runs browser automation tasks concurrently on configurable '
                              'intervals',
               'featured': True,
               'files': [{'source': 'scheduler/main.py', 'dest': 'main.py'},
                         {'source': 'scheduler/agents/gmail.py', 'dest': 'agents/gmail.py'},
                         {'source': 'scheduler/agents/x.py', 'dest': 'agents/x.py'},
                         {'source': 'scheduler/pyproject.toml.template', 'dest': 'pyproject.toml'},
                         {'source': 'scheduler/.env.example.template', 'dest': '.env.example'},
                         {'source': 'gitignore.template', 'dest': '.gitignore'},
                         {'source': 'scheduler/README.md', 'dest': 'README.md'}],
               'next_steps': [{'title': 'Navigate to project directory', 'commands': ['cd {template}']},
                              {'title': 'Set up your API key and cloud settings',
                               'commands': ['cp .env.example .env',
                                            '# Edit .env and add your BROWSER_USE_API_KEY and optional cloud settings'],
                               'note': '(Get your API key at https://cloud.browser-use.com/new-api-key)'},
                              {'title': 'Install dependencies', 'commands': ['uv sync']},
                              {'title': 'Run the scheduler', 'commands': ['uv run {output}']},
                              {'footer': '📖 See README.md for adding custom agents, configuration, and '
                                         'troubleshooting\n'
                                         '\n'
                                         '🔄 The scheduler will auto-discover all .py files in the agents/ directory'}],
               'author': {'name': 'Shawn Pana',
                          'github_profile': 'https://github.com/ShawnPana',
                          'last_modified_date': '2025-11-14'}}}

TRUSTED_INIT_TEMPLATE_HASHES = {'default_template.py': 'sha256:2786b926196dcb8cf4e9a37a6fa830a623bcc8c35329bcdac022d36a05897574',
 'advanced_template.py': 'sha256:4ad638db292622cc3701bd16cfe9476c6dc68c4e4da28be5d40849859c627d38',
 'tools_template.py': 'sha256:5b3850bbd1e10f62d56199ba03070526b658e1eafa67a73e25e52f041ce8a778',
 'sandbox/main.py': 'sha256:562c96d64f23a81c8cc33e0299d174c2bd65b023fd11d348a71c8a33a543980b',
 'sandbox/pyproject.toml.template': 'sha256:e0da0a8c62d01a5926350e62bb6315e802aa29573690afff5bad9d260d4339ce',
 'gitignore.template': 'sha256:7f6197bf9efce61a901f7c836d5b854fd3f3a687f5c4b60aa2c01eb13a2ab137',
 'sandbox/.env.example.template': 'sha256:e357d28d032c155996c1dc2e2f51d0d6d2b807c91398dc195f2f9c0e83878a2b',
 'sandbox/README.md': 'sha256:29a25f42945a4968763b2e79ec58153c6ac28510bfd5129663d82fa42e71d7b0',
 'shopping/main.py': 'sha256:1e256552217f770d81d5f0f976111a82d8563bb4fede5f5618e05aa820fec7e0',
 'shopping/launch_chrome_debug.py': 'sha256:a985b6c0c255575455a78999428c60904648151c7093f6287eb03c57fbdf74f9',
 'shopping/pyproject.toml.template': 'sha256:cd86c1fed589d8148ac1cc0148a8900dcd48498b5f50efc46900e764fffe7dff',
 'shopping/.env.example.template': 'sha256:8c732e83970c6b0637ecf47025afcf122580f430063925b9217d56885d933ece',
 'shopping/README.md': 'sha256:49d0609f7b2d46dd7f1e122760932f16a3f71325bbef2c1f5fbf885225be8ce5',
 'job-application/main.py': 'sha256:b0460ac996e4a376b94b093bc908750d7a2a4b6e71c394d5bead927169d6dfdc',
 'job-application/pyproject.toml.template': 'sha256:fb248454a3ef90e4416028a9461bc7142cb3886a0b309b29e483987338196c11',
 'job-application/.env.example.template': 'sha256:478b582a07375698ed7c6a681a69766a376351c9c77f39a2e75aeeef485eab20',
 'job-application/README.md': 'sha256:633e15fa2c3e12cf0893edcce85f5fbe8a8922af42c9e0c05a006ad08b6d4f68',
 'job-application/applicant_data.json': 'sha256:8ea669ad2a4ed52db8676cd3db2a8f3556a9bd8726d122750b1a04de7f563bc0',
 'job-application/example_resume.pdf': 'sha256:95ebebe9489f467d5ecaa989f0d6e601364547c08bc57a02fb0c2fe816388a18',
 'agentmail/main.py': 'sha256:c5ff42dd869dfac8bdec73137362c9e84148a6f669255ac9b28c1cd1417b5fb2',
 'agentmail/email_tools.py': 'sha256:08b379f4ffe312b556f6d736bd0f4101139dfbcd772154f080c0f117fd9b2120',
 'agentmail/pyproject.toml.template': 'sha256:bfcd4476dc338ea6b418b738757b38bea10d472c6da08a9c87269c9103aaaab6',
 'agentmail/.env.example.template': 'sha256:7fbaafba3d522ff61e80f27adb8ff2ae89b3198c4c9199eb50ecbf42a423044a',
 'agentmail/README.md': 'sha256:c3101e8b1ed8e8f2a5232afcd2c65d76aaf4f4de13645d1c370d8fad5179de1b',
 'llm-arena/main.py': 'sha256:11f6e751ee0409a56702eae46ac47d489343a8861406f9d4ff4ee1d028c86739',
 'llm-arena/pyproject.toml.template': 'sha256:8f30bf5a09965988b627a055c7b7948ea8b54e92a04745068bac10884a83044d',
 'llm-arena/.env.example.template': 'sha256:e0ab1c2baef61dd1a08a77cea359fa5c5340128b9014b3b3936cdbee5b195494',
 'llm-arena/README.md': 'sha256:713e8fdb275c66c9df70e68fcecd7ed139db555f2a077b3bb22c979da2b51348',
 'slack/app/main.py': 'sha256:fcbabbff8899a520aed014fad155bf8b5a91266c39d60ca855c993a64e0b6d10',
 'slack/app/service.py': 'sha256:a6974f20b90390442eec38571d1e22f91c5bb7ecb63ef34d194785b83cd70e60',
 'slack/pyproject.toml.template': 'sha256:a32ef287248627f2c1a5ab76adeaeaa4a3436e3586191bf25fe6dc6c777f9435',
 'slack/.env.example.template': 'sha256:70cc178f9e12ad4723d2e1425dc352fb60b9d435404560716f30ca992dbf8f3c',
 'slack/README.md': 'sha256:f752cc79d0e2d85e7aba350864bfb4be41538d3ff34bf02004cf0dd699c543eb',
 'all-openai-jobs/main.py': 'sha256:d41d84d2e888e0dd96bae467dc32d2f6fd13065ba26358f73e3d4d2d56c17e60',
 'all-openai-jobs/pyproject.toml.template': 'sha256:1df1aad8a5b5f52fecbb3fadde389a8a498c712293676d87bb574ce0177de764',
 'all-openai-jobs/.env.example.template': 'sha256:c09793f4dbb692e3d8165ae051946fc4e1222af59560ac90c696c0571ecd5cda',
 'all-openai-jobs/README.md': 'sha256:02ca20ecd9b3500688422c9b393b31a54b7ee1985c076b64fa4040b179d96ea0',
 'scheduler/main.py': 'sha256:45a46a63f98acbc9e8fca7bf94a65b735ffcb4d67f435bc1777115eb9f996e10',
 'scheduler/agents/gmail.py': 'sha256:10a49bd97eed085bed56c280047c55a7b0502676ffc2a371aa3eefedd375110e',
 'scheduler/agents/x.py': 'sha256:c9fdcb87a50c6a46c77beea77b898b541025bc0f91bad7c0a896aab35ba088eb',
 'scheduler/pyproject.toml.template': 'sha256:29701de70d88d24324089cbbe2df63dc9e793db758a2ab02de1ee4edf074f622',
 'scheduler/.env.example.template': 'sha256:dc5ce4d2a309d69952abf7c32d868566ecf26a0ba98a1fdeb31dc92a4bdade1b',
 'scheduler/README.md': 'sha256:eb3f282b99349d471a028d205bf11bd842146b778087ffad12e948df9508f787'}
