name: ci
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - uses: pre-commit/action@v3.0.1

  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install --upgrade pip
      # - run: pip install pytest
      - run: pip install --editable ".[dev]"
      - run: playwright install --with-deps
      # TODO: Add a GitHub Actions secrets.OPENAI_API_KEY and enable the ignored tests
      # openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable
      - run: pytest --continue-on-collection-errors
      #              --deselect=tests/test_context.py::test_get_initial_state
      #              --deselect=tests/test_service.py::TestAgent::test_convert_initial_actions
      #              --ignore=tests/test_dropdown_error.py
      #              --ignore=tests/test_gif_path.py
      #              --ignore=tests/test_models.py
      #              --ignore=tests/test_react_dropdown.py
      #              --ignore=tests/test_save_conversation.py
      #              --ignore=tests/test_vision.py
